title:                  "Chassis - Docs"
baseURL:                "https://chassis-ui.com"

docsDir:                "site"

subtitle:               "Documentation for the Chassis design system."
description:            "Comprehensive documentation for Chassis CSS framework, design tokens, and Figma components."
authors:                "Ozgur Gunes and Bootstrap contributors"

current_version:        "0.1.0"
current_ruby_version:   "0.1.0"
docs_version:           "0.1"
rfs_version:            "v10.0.0"
github_org:             "https://github.com/ozgurgunes"
repo:                   "https://github.com/ozgurgunes/chassis-docs"
x:                      "chassis_ui"

analytics:
  google_id:               "G-QGR8C28VYN"

algolia:
  app_id:               "MEJ97SH293"
  api_key:              "df6a517a37c3973122cfc40042055f9c"
  index_name:           "chassis-docs"

blog:
  pageSize:             2

download:
  source:               "https://github.com/ozgurgunes/chassis-docs/archive/v0.1.0.zip"
  dist:                 "https://github.com/ozgurgunes/chassis-docs/releases/download/v0.1.0/chassis-docs-0.1.0-dist.zip"
  dist_examples:        "https://github.com/ozgurgunes/chassis-docs/releases/download/v0.1.0/chassis-docs-0.1.0-examples.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:                  "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/css/chassis-css.min.css"
  css_hash:             "sha384-z1z0pR6Kr5Cie6j3tj9zBdR43rQ/19OUDRvLf67MnVBXC2rrIv6KomMcS+7cDrEX"
  css_rtl:              "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/css/chassis-css.rtl.min.css"
  css_rtl_hash:         "sha384-FtQ/A8+7/yGOF6t87QXic08Pn3anj3iAuo948JtneeerUvzL+pfC6vyPu3HRVBlz"
  js:                   "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/js/chassis-css.min.js"
  js_hash:              "sha384-NUR67mCgsLSPLPAkVb32tnNlQdGAfOk/PH4iDWd8UArTrE5mEiDrHmeajFrGm9Up"
  js_bundle:            "https://cdn.jsdelivr.net/npm/chassis-css@0.1.0/dist/js/chassis-css.bundle.min.js"
  js_bundle_hash:       "sha384-MKU9WDEVXmku6o36KR2LmSuQ2YKtDx8+/y0rgWX6fbxS8SucAN86y8vVIWKX+uCV"
  popper:               "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
  popper_hash:          "sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
  popper_esm:           "https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/esm/popper.min.js"

anchors:
  min:                  2
  max:                  5

toc:
  min:                  2
  max:                  6
