/**
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * This file is automatically generated by the Chassis Astro Integration.
 * It contains the type definitions for the components that are auto imported in all pages.
 * @see site/src/libs/astro.ts
 */
export declare global {
  export const Code: typeof import('@shortcodes/Code.astro').default
  export const CxTable: typeof import('@shortcodes/CxTable.astro').default
  export const Example: typeof import('@shortcodes/Example.astro').default
}
