name: Deploy Documentation

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/website/package-lock.json
          
      - name: Install dependencies
        working-directory: apps/website
        run: npm ci
        
      - name: Sync submodules
        run: |
          git submodule update --remote --merge
          npm run sync:all
          
      - name: Set environment variables
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "VERCEL_ENV=production" >> $GITHUB_ENV
            echo "DEPLOYMENT_URL=chassis-ui.com" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/staging" ]; then
            echo "VERCEL_ENV=preview" >> $GITHUB_ENV
            echo "DEPLOYMENT_URL=staging.chassis-ui.com" >> $GITHUB_ENV
          fi
          
      - name: Build website
        working-directory: apps/website
        run: npm run build
        
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: apps/website
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
